# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class V8s < Formula
  desc "kubernetes controller for vince- The Cloud Native Web Analytics Platform"
  homepage "httpd://vinceanalytics.github.io"
  version "0.0.18"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.18/v8s_darwin_arm64.tar.gz"
      sha256 "8b792fc4498edd5f7eecec17194d5c5702bf8dc9d8de205e5b5d15f73e2db9d8"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.18/v8s_darwin_x86_64.tar.gz"
      sha256 "af7fb0e4b957bb4513f2f186f06daca67cb22ad16f52587786875b52202e686f"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.18/v8s_linux_arm64.tar.gz"
      sha256 "e3569d566412cadf2c7eae561662dfbf669c7b62ee94e55cfa08518f5898ad86"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.18/v8s_linux_x86_64.tar.gz"
      sha256 "92696476b5cd1db40b444dc2bc629ca3a0a6e873a11fa9dbd5566611dc8ab249"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
  end

  test do
    system "#{bin}/v8s version"
  end
end
