# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class V8s < Formula
  desc "kubernetes controller for vince- The Cloud Native Web Analytics Platform"
  homepage "httpd://vinceanalytics.github.io"
  version "0.0.15"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.15/v8s_darwin_arm64.tar.gz"
      sha256 "3c42ab26fdf7572ac675fbd3391e245babf8bd5ed11443c73ebb7a2bde6e3b23"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.15/v8s_darwin_x86_64.tar.gz"
      sha256 "109542fb06f0e5c95d05946c09f5e60e5877e0f15b1c8bf15a17a58c3ca73289"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.15/v8s_linux_arm64.tar.gz"
      sha256 "0bc02de7177cdb4c006d289701aa765b8015776e13a4f5a458cc42bb1bcd8422"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.15/v8s_linux_x86_64.tar.gz"
      sha256 "acb7714c312def561eb2ac0c240ba3fb26fa0cf234070a10ffb1505a44d404ad"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
  end

  test do
    system "#{bin}/v8s version"
  end
end
