# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class V8s < Formula
  desc "kubernetes controller for vince- The Cloud Native Web Analytics Platform"
  homepage "httpd://vinceanalytics.github.io"
  version "0.0.16"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.16/v8s_darwin_arm64.tar.gz"
      sha256 "d31fc3b3674d6f550d856574246e5d7f0b669c40fe5a0b43d25b591dcd3e7316"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.16/v8s_darwin_x86_64.tar.gz"
      sha256 "78a48e7ae69ddfba366c57d2358650d38c94961d6e4b29c60e3e97b077b3e238"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.16/v8s_linux_arm64.tar.gz"
      sha256 "3f362301c0c79a1f68333ffdb38e590795026a7a4fddc120dfb9b480142d97de"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.16/v8s_linux_x86_64.tar.gz"
      sha256 "5ee0a37030d88d268716fb2619bf3af6c9266fd275a451a8df477d6a4f1a0c21"

      def install
        bin.install "v8s"
        bash_completion.install "completions/v8s/v8s.bash" => "v8s"
        zsh_completion.install "completions/v8s/v8s.zsh" => "_v8s"
        fish_completion.install "completions/v8s/v8s.fish"
        man1.install "man/v8s.1"
      end
    end
  end

  test do
    system "#{bin}/v8s version"
  end
end
