# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vince < Formula
  desc "The Cloud Native Web Analytics Platform"
  homepage "https://vinceanalytics.com"
  version "0.0.44"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.44/vince_darwin_arm64.tar.gz"
      sha256 "0e0f34824040710ddcfc35bf04d7d4ac6476653b743d28040f017edec362cd11"

      def install
        bin.install "vince"
        bash_completion.install "completions/vince/vince.bash" => "vince"
        zsh_completion.install "completions/vince/vince.zsh" => "_vince"
        fish_completion.install "completions/vince/vince.fish"
        man1.install "man/vince.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.44/vince_darwin_x86_64.tar.gz"
      sha256 "a25c219eb7a999a2217470fd5117f99f7afe740e362a0c3f267419e6f1359127"

      def install
        bin.install "vince"
        bash_completion.install "completions/vince/vince.bash" => "vince"
        zsh_completion.install "completions/vince/vince.zsh" => "_vince"
        fish_completion.install "completions/vince/vince.fish"
        man1.install "man/vince.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.44/vince_linux_arm64.tar.gz"
      sha256 "3d23102fade6ac4cb3fc8ec9a9c8a1cd4bd9287d2f2e554e924d36958602d232"

      def install
        bin.install "vince"
        bash_completion.install "completions/vince/vince.bash" => "vince"
        zsh_completion.install "completions/vince/vince.zsh" => "_vince"
        fish_completion.install "completions/vince/vince.fish"
        man1.install "man/vince.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.44/vince_linux_x86_64.tar.gz"
      sha256 "a127b5905f83399a85feee941c656b6b59144a1b76931588a2d8d8b62527a227"

      def install
        bin.install "vince"
        bash_completion.install "completions/vince/vince.bash" => "vince"
        zsh_completion.install "completions/vince/vince.zsh" => "_vince"
        fish_completion.install "completions/vince/vince.fish"
        man1.install "man/vince.1"
      end
    end
  end

  test do
    system "#{bin}/vince --version"
  end
end
