# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vince < Formula
  desc "The Cloud Native Web Analytics Platform"
  homepage "https://vinceanalytics.com"
  version "0.0.43"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.43/vince_darwin_x86_64.tar.gz"
      sha256 "e5ab8ef06af5f671e683c7bb5b77efec00c481b91ea08c5ee31f5e78b279c76e"

      def install
        bin.install "vince"
        bash_completion.install "completions/vince/vince.bash" => "vince"
        zsh_completion.install "completions/vince/vince.zsh" => "_vince"
        fish_completion.install "completions/vince/vince.fish"
        man1.install "man/vince.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.43/vince_darwin_arm64.tar.gz"
      sha256 "584eef495894d584063d45d32bd9da214d9f02dfaa9cd64d80f745b6bf5fcc55"

      def install
        bin.install "vince"
        bash_completion.install "completions/vince/vince.bash" => "vince"
        zsh_completion.install "completions/vince/vince.zsh" => "_vince"
        fish_completion.install "completions/vince/vince.fish"
        man1.install "man/vince.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.43/vince_linux_x86_64.tar.gz"
      sha256 "a0cd2be1e2c678f32a532c0d4a5915ee31988f735c8b5f1d82ede47df9d02479"

      def install
        bin.install "vince"
        bash_completion.install "completions/vince/vince.bash" => "vince"
        zsh_completion.install "completions/vince/vince.zsh" => "_vince"
        fish_completion.install "completions/vince/vince.fish"
        man1.install "man/vince.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vinceanalytics/vince/releases/download/v0.0.43/vince_linux_arm64.tar.gz"
      sha256 "eb5ee75c1c25e5fe89d4bf211902a496793b9bf4bed2d7a5fc131a91309d21f5"

      def install
        bin.install "vince"
        bash_completion.install "completions/vince/vince.bash" => "vince"
        zsh_completion.install "completions/vince/vince.zsh" => "_vince"
        fish_completion.install "completions/vince/vince.fish"
        man1.install "man/vince.1"
      end
    end
  end

  test do
    system "#{bin}/vince --version"
  end
end
